### ISSUE TITLE
简单预览界面，点开第二张图然后滑动到第三张图 拖拽关闭预览时崩溃

### ISSUE THREAD

**Issue by dccice** [albert-lii/ImageViewer#10]
Process: com.liyi.example, PID: 22874
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'float com.liyi.viewer.ViewData.getTargetX()' on a null object reference
                                                                      at com.liyi.viewer.dragger.WxImageDragger.exit(WxImageDragger.java:179)
                                                                      at com.liyi.viewer.dragger.WxImageDragger.onRelease(WxImageDragger.java:108)
                                                                      at com.liyi.viewer.widget.ScaleImageView.onActionUp(ScaleImageView.java:212)
                                                                      at com.liyi.viewer.widget.ScaleImageView.onTouchEvent(ScaleImageView.java:189)
                                                                      at android.view.View.dispatchTouchEvent(View.java:9302)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2590)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2596)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2596)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2596)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2596)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2596)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2596)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2271)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2408)
                                                                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1742)
                                                                      at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2369)
                                                                      at android.view.View.dispatchPointerEvent(View.java:9522)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4729)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4593)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4137)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4190)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4156)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4282)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4164)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4339)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4137)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4190)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4156)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4164)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4137)
                                                                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6461)
                                                                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6427)
                                                                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6388)
                                                                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6571)
                                                                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                      at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                      at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by albert-lii** [comment]
你好，谢谢你的反馈，已修复该bug
