### ISSUE TITLE
demo随便打开一张图，然后一直双指合并缩小，崩溃

### ISSUE THREAD

**Issue by imyyq-star** [albert-lii/ImageViewer#9]
java.lang.IllegalArgumentException: pointerIndex out of range
                                                                      at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                      at android.view.MotionEvent.getX(MotionEvent.java:2201)
                                                                      at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
                                                                      at com.liyi.viewer.widget.viewpager.ImagePager.onInterceptTouchEvent(ImagePager.java:68)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2511)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                                                                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
                                                                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
                                                                      at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
                                                                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
                                                                      at android.view.View.dispatchPointerEvent(View.java:12015)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
                                                                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
                                                                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
                                                                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
                                                                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
                                                                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
                                                                      at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                      at android.os.MessageQueue.next(MessageQueue.java:325)
                                                                      at android.os.Looper.loop(Looper.java:142)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by albert-lii** [comment]
已做修复
